#!/usr/bin/env bash
# 30-traefik.sh — install Traefik as a NodePort ingress controller.
#
# WHY NodePort AND NOT LoadBalancer:
#
#   On a single-node k3s, a Service of type LoadBalancer is served by svclb,
#   which grabs host ports 80 and 443 directly. Caddy already owns those ports
#   on this host — it terminates TLS and reverse-proxies to the NodePort — so a
#   LoadBalancer Traefik would either fail to bind or steal the traffic. The
#   chain is Caddy -> 127.0.0.1:30080 -> Traefik, and NodePort is what makes
#   that chain legal.
#
# WHY kubernetesCRD IS DISABLED:
#
#   With CRDs enabled, Traefik accepts IngressRoute objects. Manifests written
#   against IngressRoute are not portable to any other controller, and the
#   IngressRoute CRDs would need to be installed and owned by this repo. With
#   CRDs off, standard Ingress is the ONLY option — not merely the preferred
#   one — which is the more honest posture for a portable portfolio artefact.
#   Verified against the installed controller, not against chart defaults:
#   `helm get values` plus the deployment's rendered container args.
#
# WHY ingressEndpoint.ip IS SET AND publishedService IS DISABLED:
#
#   Argo CD marks an Ingress as Progressing until `status.loadBalancer.ingress`
#   is populated. A NodePort Service never populates it, so the Ingress never
#   becomes Healthy and Argo sits at Synced/Progressing forever while the app
#   serves 200s — a false alarm generated by the monitoring rather than the app.
#
#   Traefik's default `ingressendpoint.publishedservice=traefik/traefik` points
#   at exactly that status-less Service, so it publishes nothing. It must be
#   turned OFF, because publishedService takes PRECEDENCE over the static value
#   and silently wins; setting only the IP produces no visible change and looks
#   like the flag did nothing.
#
#   A static IP is truthful only while there is exactly one controller and one
#   host behind it. The moment a second host exists, MetalLB is the correct
#   answer, because it gives the Service a real loadBalancer.ingress.
#
# IDEMPOTENT: `helm upgrade --install` with an explicit full --set list. The
# --set list is spelled out in full rather than layered, because helm's --set
# does NOT validate key paths: a typo'd key is accepted and silently ignored
# (finding 7), so every value is read back from the rendered object at the end.

set -euo pipefail

readonly NS="traefik"
readonly RELEASE="traefik"
readonly CHART="traefik/traefik"
readonly ENDPOINT_IP="${TRAEFIK_ENDPOINT_IP:-}"
readonly NODEPORT_HTTP=30080
readonly NODEPORT_HTTPS=30443

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
ok()   { printf '  ok   %s\n' "$1"; }
note() { printf '  ..   %s\n' "$1"; }

export PATH="$HOME/.local/bin:$PATH"
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

printf '== traefik ==\n'

[ -n "$ENDPOINT_IP" ] || fail "set TRAEFIK_ENDPOINT_IP to this node's address, e.g.:
  TRAEFIK_ENDPOINT_IP=10.0.0.1 $0"

# --- helm repo ----------------------------------------------------------------
# `helm` needs the kubeconfig, which is root-only by design (finding 6). Every
# helm call here therefore runs under sudo -E, or it fails with a permission
# error that reads like a network problem.
if ! sudo -E helm repo list 2>/dev/null | grep -q '^traefik'; then
  note "adding the traefik helm repo"
  sudo -E helm repo add traefik https://traefik.github.io/charts
fi
sudo -E helm repo update traefik >/dev/null

# --- install / upgrade --------------------------------------------------------
# Every --set below is load-bearing and none is a chart default worth keeping.
note "installing $RELEASE (NodePort ${NODEPORT_HTTP}/${NODEPORT_HTTPS}, CRDs off, endpoint ${ENDPOINT_IP})"
sudo -E helm upgrade --install "$RELEASE" "$CHART" -n "$NS" --create-namespace \
  --set ingressRoute.dashboard.enabled=false \
  --set ports.web.nodePort="$NODEPORT_HTTP" \
  --set ports.websecure.nodePort="$NODEPORT_HTTPS" \
  --set providers.kubernetesCRD.enabled=false \
  --set providers.kubernetesIngress.enabled=true \
  --set providers.kubernetesIngress.publishedService.enabled=false \
  --set providers.kubernetesIngress.ingressEndpoint.ip="$ENDPOINT_IP" \
  --set service.spec.type=NodePort \
  --wait --timeout 240s

# --- read the rendered object back -------------------------------------------
# helm accepted --set without validating the key paths. The only trustworthy
# source is the running Deployment's args.
args="$(sudo -E k3s kubectl -n "$NS" get deploy "$RELEASE" \
  -o jsonpath='{range .spec.template.spec.containers[0].args[*]}{.}{"\n"}{end}')"

assert_arg() {
  printf '%s\n' "$args" | grep -qx -- "$1" || fail "rendered args missing: $1"
  ok "arg $1"
}
assert_arg "--providers.kubernetesingress.ingressendpoint.ip=$ENDPOINT_IP"
assert_arg "--providers.kubernetesingress.allowEmptyServices=true"

if printf '%s\n' "$args" | grep -q 'ingressendpoint.publishedservice'; then
  fail "publishedservice is still set — it takes precedence and will publish nothing"
fi
ok "publishedservice absent (static endpoint is authoritative)"

# --- service shape -----------------------------------------------------------
type="$(sudo -E k3s kubectl -n "$NS" get svc "$RELEASE" -o jsonpath='{.spec.type}')"
[ "$type" = "NodePort" ] || fail "traefik Service is type $type, expected NodePort"
ok "Service type NodePort"

ports="$(sudo -E k3s kubectl -n "$NS" get svc "$RELEASE" \
  -o jsonpath='{range .spec.ports[*]}{.nodePort}{" "}{end}')"
printf '%s' "$ports" | grep -qw "$NODEPORT_HTTP"  || fail "web NodePort not $NODEPORT_HTTP"
printf '%s' "$ports" | grep -qw "$NODEPORT_HTTPS" || fail "websecure NodePort not $NODEPORT_HTTPS"
ok "NodePorts: $ports"

if sudo -E k3s kubectl -n kube-system get pods 2>/dev/null | grep -qi svclb; then
  fail "svclb is present — it will fight Caddy for host ports 80/443"
fi
ok "no svclb"

# --- the whole chain, end to end ---------------------------------------------
note "asserting Traefik answers on its NodePort"
for _ in $(seq 1 30); do
  if curl -sf -o /dev/null "http://127.0.0.1:${NODEPORT_HTTP}" 2>/dev/null \
     || curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${NODEPORT_HTTP}" 2>/dev/null | grep -qE '^(200|404)$'; then
    break
  fi
  sleep 2
done
code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${NODEPORT_HTTP}" || true)"
[ "$code" = "404" ] || [ "$code" = "200" ] \
  || fail "Traefik NodePort did not answer (got '$code'); a bare controller with no matching Ingress should 404"
ok "Traefik answers on :${NODEPORT_HTTP} (HTTP $code)"

sudo -E k3s kubectl -n "$NS" get pods

printf '\nTRAEFIK OK\n'
