#!/usr/bin/env bash
# 30-traefik.sh - install Traefik as a NodePort ingress controller.
#
# WHY NodePort AND NOT LoadBalancer:
#
#   On a single-node k3s, a Service of type LoadBalancer is served by svclb,
#   which grabs host ports 80 and 443 directly. Caddy already owns those ports
#   on this host - it terminates TLS and reverse-proxies to the NodePort - so a
#   LoadBalancer Traefik would either fail to bind or steal the traffic. The
#   chain is cloudflared tunnel -> 127.0.0.1:30080 -> Traefik, and NodePort is what makes
#   that chain legal.
#
# WHY kubernetesCRD IS ENABLED:
#
#   Traefik then accepts IngressRoute objects and Middleware. AskVault's edge
#   uses both: IngressRoute keeps the L2 exact-path contract expressible, and
#   Middleware carries the prod policy (security headers, edge rate cap, read
#   path retry) instead of scattering it into the app. The known trade-off is
#   portability - IngressRoute is Traefik-flavoured, not controller-agnostic -
#   and the CRDs are owned by the Traefik chart. The standard Ingress provider
#   stays enabled in parallel, so plain Ingress remains a supported route for
#   anything that prefers it (the portability fallback is documented, not
#   broken). Verified against the installed controller, not against chart
#   defaults: `helm get values` plus the deployment's rendered container args.
#
# WHY ingressEndpoint.ip IS SET AND publishedService IS DISABLED:
#
#   Argo CD marks an Ingress as Progressing until `status.loadBalancer.ingress`
#   is populated. A NodePort Service never populates it, so the Ingress never
#   becomes Healthy and Argo sits at Synced/Progressing forever while the app
#   serves 200s - a false alarm generated by the monitoring rather than the app.
#
#   Traefik's default `ingressendpoint.publishedservice=traefik/traefik` points
#   at exactly that status-less Service, so it publishes nothing. It must be
#   turned OFF, because publishedService takes PRECEDENCE over the static value
#   and silently wins; setting only the IP produces no visible change and looks
#   like the flag did nothing.
#
#   A static IP is truthful only while there is exactly one controller and one
#   host behind it. The moment a second host exists, MetalLB is the correct
#   answer, because it gives the Service a real loadBalancer.ingress.
#
# IDEMPOTENT: `helm upgrade --install` with an explicit full --set list. The
# --set list is spelled out in full rather than layered, because helm's --set
# does NOT validate key paths: a typo'd key is accepted and silently ignored
# (finding 7), so every value is read back from the rendered object at the end.

set -euo pipefail

readonly NS="traefik"
readonly RELEASE="traefik"
readonly CHART="traefik/traefik"
readonly NODEPORT_HTTP=30080
readonly NODEPORT_HTTPS=30443

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
ok()   { printf '  ok   %s\n' "$1"; }
note() { printf '  ..   %s\n' "$1"; }

export PATH="$HOME/.local/bin:$PATH"
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

printf '== traefik ==\n'

# --- the endpoint IP ----------------------------------------------------------
# This is the address Traefik publishes on its Ingresses so Argo can report them
# Healthy. Hardcoding it in the script would be wrong, but demanding it by hand
# was unnecessary friction: the host already knows its own addresses.
#
# AUTO-DETECT, in order of preference, with an explicit override.
#
# The Tailscale address is preferred because that is the interface Caddy binds
# to, which is the whole reason Traefik is NodePort. A bare LAN IP would be
# resolvable from fewer places; a public IP would be exposed.
detect_endpoint_ip() {
  # 1. An explicit override always wins.
  if [ -n "${TRAEFIK_ENDPOINT_IP:-}" ]; then
    printf '%s' "$TRAEFIK_ENDPOINT_IP"
    return 0
  fi

  # 2. The Tailscale interface, if this host is on a tailnet.
  if command -v tailscale >/dev/null 2>&1; then
    ip="$(tailscale ip -4 2>/dev/null | head -1)"
    [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  fi

  # 3. The node's internal address, as Kubernetes itself sees it. This is the
  #    most portable option: it exists on any k3s node with no extra tooling.
  ip="$(sudo -E k3s kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' 2>/dev/null)"
  [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }

  return 1
}

if ! ENDPOINT_IP="$(detect_endpoint_ip)"; then
  fail "could not determine this node's address.
Set it explicitly:
  TRAEFIK_ENDPOINT_IP=<address> $0"
fi
note "endpoint IP: $ENDPOINT_IP (override with TRAEFIK_ENDPOINT_IP)"

# --- helm repo ----------------------------------------------------------------
# `helm` needs the kubeconfig, which is root-only by design (finding 6). Every
# helm call here therefore runs under sudo -E, or it fails with a permission
# error that reads like a network problem.
if ! sudo -E helm repo list 2>/dev/null | grep -q '^traefik'; then
  note "adding the traefik helm repo"
  sudo -E helm repo add traefik https://traefik.github.io/charts
fi
sudo -E helm repo update traefik >/dev/null

# --- install / upgrade --------------------------------------------------------
# Every --set below is load-bearing and none is a chart default worth keeping.
note "installing $RELEASE (NodePort ${NODEPORT_HTTP}/${NODEPORT_HTTPS}, CRDs on: IngressRoute + Middleware, endpoint ${ENDPOINT_IP})"
sudo -E helm upgrade --install "$RELEASE" "$CHART" -n "$NS" --create-namespace \
  --set ingressRoute.dashboard.enabled=false \
  --set ports.web.nodePort="$NODEPORT_HTTP" \
  --set ports.websecure.nodePort="$NODEPORT_HTTPS" \
  --set providers.kubernetesCRD.enabled=true \
  --set providers.kubernetesIngress.enabled=true \
  --set providers.kubernetesIngress.publishedService.enabled=false \
  --set providers.kubernetesIngress.ingressEndpoint.ip="$ENDPOINT_IP" \
  --set service.spec.type=NodePort \
  --wait --timeout 240s

# --- read the rendered object back -------------------------------------------
# helm accepted --set without validating the key paths. The only trustworthy
# source is the running Deployment's args.
#
# BUG FOUND ON THE FIRST BARE-HOST RUN, 2026-09-26, and it was in this script's
# own ASSERTION rather than in the install. The original used:
#     -o jsonpath='{range .spec.template.spec.containers[0].args[*]}{.}{"\n"}{end}'
# which returns a perfectly good list when run by hand, but an EMPTY STRING
# when run from inside this script. The nested quoting in the jsonpath range
# expression does not survive the layering. The result was a false failure
# claiming a flag was missing when it was present the whole time - the same
# class of error as findings 26 and 28: a check that reports on itself rather
# than on the thing it claims to check.
#
# jq is used instead. It is already a dependency of the drill, it takes JSON on
# stdin rather than a format string, and one value per line needs no escaping.
args="$(sudo -E k3s kubectl -n "$NS" get deploy "$RELEASE" -o json 2>/dev/null \
  | jq -r '.spec.template.spec.containers[0].args[]' 2>/dev/null || true)"
[ -n "$args" ] || fail "could not read the rendered args - the Deployment may not exist yet"

assert_arg() {
  # `grep -Fxq` with the pattern after `--`: -F makes it literal (the values
  # contain `.` and `:`), -x requires a whole-line match so a prefix does not
  # count, and `--` stops a leading dash being parsed as an option. With -x -F
  # the leading `--` in the pattern is fine; it is only a problem when grep is
  # asked to interpret the pattern as regex or as options.
  printf '%s\n' "$args" | grep -Fxq -- "$1" || fail "rendered args missing: $1"
  ok "arg $1"
}
assert_arg "--providers.kubernetesingress.ingressendpoint.ip=$ENDPOINT_IP"
assert_arg "--providers.kubernetesingress.allowEmptyServices=true"

if printf '%s\n' "$args" | grep -q 'ingressendpoint.publishedservice'; then
  fail "publishedservice is still set - it takes precedence and will publish nothing"
fi
ok "publishedservice absent (static endpoint is authoritative)"

# --- service shape -----------------------------------------------------------
type="$(sudo -E k3s kubectl -n "$NS" get svc "$RELEASE" -o jsonpath='{.spec.type}')"
[ "$type" = "NodePort" ] || fail "traefik Service is type $type, expected NodePort"
ok "Service type NodePort"

ports="$(sudo -E k3s kubectl -n "$NS" get svc "$RELEASE" \
  -o jsonpath='{range .spec.ports[*]}{.nodePort}{" "}{end}')"
printf '%s' "$ports" | grep -qw "$NODEPORT_HTTP"  || fail "web NodePort not $NODEPORT_HTTP"
printf '%s' "$ports" | grep -qw "$NODEPORT_HTTPS" || fail "websecure NodePort not $NODEPORT_HTTPS"
ok "NodePorts: $ports"

if sudo -E k3s kubectl -n kube-system get pods 2>/dev/null | grep -qi svclb; then
  fail "svclb is present - it will fight Caddy for host ports 80/443"
fi
ok "no svclb"

# --- the whole chain, end to end ---------------------------------------------
note "asserting Traefik answers on its NodePort"
for _ in $(seq 1 30); do
  if curl -sf -o /dev/null "http://127.0.0.1:${NODEPORT_HTTP}" 2>/dev/null \
     || curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${NODEPORT_HTTP}" 2>/dev/null | grep -qE '^(200|404)$'; then
    break
  fi
  sleep 2
done
code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${NODEPORT_HTTP}" || true)"
[ "$code" = "404" ] || [ "$code" = "200" ] \
  || fail "Traefik NodePort did not answer (got '$code'); a bare controller with no matching Ingress should 404"
ok "Traefik answers on :${NODEPORT_HTTP} (HTTP $code)"

sudo -E k3s kubectl -n "$NS" get pods

printf '\nTRAEFIK OK\n'
